apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "darts-web.fullname" . }}
  labels:
    {{- include "darts-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3  # Beh√§lt nur die letzten 3 ReplicaSets
  selector:
    matchLabels:
      {{- include "darts-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "darts-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_PATH
              value: {{ .Values.config.dbPath | quote }}
            - name: BASE_PATH
              value: {{ .Values.config.basePath | quote }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "darts-web.fullname" . }}-pvc
      {{- end }}
