# Default values for darts-web.

replicaCount: 1

image:
  repository: darts-app
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.13"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: ""
  annotations: 
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: mini-pc
      paths:
        - path: /darts
          pathType: Prefix

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"

config:
  basePath: "/darts"
  dbPath: "/data/darts.db"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
